# ml/Dockerfile
FROM python:3.11

WORKDIR /app

# Install system dependencies for Playwright
# Install system dependencies
RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    curl \
    unzip \
    xvfb \
    libgconf-2-4 \
    libxss1 \
    libnss3 \
    libnspr4 \
    libasound2 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libgbm1 \
    libgtk-3-0 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxrandr2 \
    xdg-utils \
    fonts-liberation \
    dbus \
    xauth \
    xvfb \
    x11vnc \
    tigervnc-tools \
    supervisor \
    net-tools \
    procps \
    git \
    python3-numpy \
    fontconfig \
    fonts-dejavu \
    fonts-dejavu-core \
    fonts-dejavu-extra \
    && rm -rf /var/lib/apt/lists/*

# Copy application files
COPY . .

# Don't need to copy common directory manually since it's mounted as a volume in docker-compose.yml

# Install Python dependencies
RUN pip install -r requirements.txt

# Install Playwright and Chromium browser
RUN playwright install --with-deps chromium
RUN playwright install-deps

CMD ["python", "ml_app.py"]